# Generated by Django 5.2.4 on 2025-07-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_charity_big_hearts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team_images/')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('small_description', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15)),
            ],
        ),
    ]
