# Generated by Django 5.2.4 on 2025-08-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_charity_big_hearts', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='donation_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
