"""
Django settings for project_charity_big_hearts project.

Generated by 'django-admin startproject' using Django 5.2.4.

This file contains all the main configuration settings
for your Django project such as database, apps, middleware,
authentication, JWT, CORS, static & media files.
"""

from pathlib import Path  # Used to handle file paths in an OS-independent way

# Build paths inside the project like this: BASE_DIR / 'subdir'
# BASE_DIR points to the root directory of the project
BASE_DIR = Path(__file__).resolve().parent.parent


# -------------------- Quick-start development settings --------------------
# WARNING: These settings are NOT suitable for production

# Secret key used by Django for cryptographic signing
# ⚠️ Never expose this key in production or public repositories
SECRET_KEY = 'django-insecure-ed16q+uggkqnhln*^#jihlso)^pk)8=)m%x(+sb*)!slgp6u@v'

# DEBUG=True shows detailed error pages (helpful during development)
# Must be set to False in production
DEBUG = True

# List of allowed hosts/domain names for the project
# Empty means only localhost is allowed
ALLOWED_HOSTS = []


# -------------------- Application definition --------------------
INSTALLED_APPS = [
    'django.contrib.admin',  # Enables Django admin panel
    'django.contrib.auth',  # Handles authentication & authorization
    'django.contrib.contenttypes',  # Required for Django ORM
    'django.contrib.sessions',  # Enables session support
    'django.contrib.messages',  # Enables Django messages framework
    'django.contrib.staticfiles',  # Handles static files (CSS, JS, images)

    'rest_framework',  # Django REST Framework for building APIs
    'rest_framework_simplejwt.token_blacklist',  
    # Enables JWT token blacklisting (used during logout & token rotation)

    'corsheaders',  
    # Allows frontend apps (React, etc.) to communicate with backend API

    'app_charity_big_hearts',  # Your custom Django app

    'django_filters',  
    # Enables filtering functionality in DRF APIs
]


# -------------------- Middleware --------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  
    # Handles Cross-Origin Resource Sharing (React → Django requests)

    'django.middleware.security.SecurityMiddleware',  # Adds security-related headers
    'django.contrib.sessions.middleware.SessionMiddleware',  # Manages sessions
    'django.middleware.common.CommonMiddleware',  # Handles common HTTP tasks
    'django.middleware.csrf.CsrfViewMiddleware',  # Protects against CSRF attacks
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Adds user to requests
    'django.contrib.messages.middleware.MessageMiddleware',  # Enables messages
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Prevents clickjacking
]

# Root URL configuration file
ROOT_URLCONF = 'project_charity_big_hearts.urls'


# -------------------- Templates --------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Can be used for custom template directories
        'APP_DIRS': True,  # Enables templates inside app directories
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # Adds request to templates
                'django.contrib.auth.context_processors.auth',  # Adds user/auth data
                'django.contrib.messages.context_processors.messages',  # Adds messages
            ],
        },
    },
]

# WSGI application used by production servers
WSGI_APPLICATION = 'project_charity_big_hearts.wsgi.application'


# -------------------- Database Configuration --------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # SQLite database engine
        'NAME': BASE_DIR / 'db.sqlite3',  # Database file location
    }
}


# -------------------- Password Validation --------------------
# These validators improve password security
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        # Prevents passwords similar to username/email
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        # Enforces minimum password length
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        # Prevents common passwords like "123456"
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        # Prevents passwords containing only numbers
    },
]


# -------------------- Internationalization --------------------
LANGUAGE_CODE = 'en-us'  # Default language
TIME_ZONE = 'UTC'  # Default timezone

USE_I18N = True  # Enable internationalization
USE_TZ = True  # Enable timezone-aware datetimes


# -------------------- Static Files --------------------
STATIC_URL = 'static/'  # URL path for static files (CSS, JS)

# -------------------- Default Primary Key --------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# -------------------- CORS Settings --------------------
CORS_ALLOW_ALL_ORIGINS = True  
# Allows requests from ANY frontend (React, mobile apps, Postman, etc.)
# ⚠️ In production, this should be restricted to trusted domains


# -------------------- Django REST Framework Settings --------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # Enforces JWT authentication for protected APIs

    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
    # Enables filtering & searching in API views

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 6,  
    # API responses will return 6 items per page
}


# -------------------- JWT (Simple JWT) Settings --------------------
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    # Access token expires after 15 minutes for better security

    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # User stays logged in for 7 days

    'ROTATE_REFRESH_TOKENS': True,
    # New refresh token is generated on every refresh

    'BLACKLIST_AFTER_ROTATION': True,
    # Old refresh token is blacklisted and cannot be reused

    'UPDATE_LAST_LOGIN': True,
    # Updates user's last_login field after successful login

    'AUTH_HEADER_TYPES': ('Bearer',),
    # Authorization header format: Authorization: Bearer <token>
}


# -------------------- Media Files --------------------
MEDIA_URL = '/media/'  # URL used to access uploaded files
MEDIA_ROOT = BASE_DIR / 'media'  # Folder where uploaded files are stored
